// @formatter:off
// CHECKSTYLE:OFF
package com.ymmihw.libraries.vavr;

import io.vavr.API.Match.Pattern;
import io.vavr.API.Match.Pattern2;
import io.vavr.API.Match.Pattern3;
import java.time.LocalDate;

// GENERATED BY VAVR <<>> derived from com.ymmihw.libraries.vavr.Demo

@SuppressWarnings("deprecation")
public final class DemoPatterns {

    private DemoPatterns() {
    }

    public static <_1 extends String, _2 extends String> Pattern2<Employee, _1, _2> $Employee(Pattern<_1, ?> p1, Pattern<_2, ?> p2) {
        return Pattern2.of(Employee.class, p1, p2, com.ymmihw.libraries.vavr.Demo::Employee);
    }

    public static <_1 extends Integer, _2 extends Integer, _3 extends Integer> Pattern3<LocalDate, _1, _2, _3> $LocalDate(Pattern<_1, ?> p1, Pattern<_2, ?> p2, Pattern<_3, ?> p3) {
        return Pattern3.of(LocalDate.class, p1, p2, p3, com.ymmihw.libraries.vavr.Demo::LocalDate);
    }

}
// CHECKSTYLE:ON
// @formatter:on