## Server properties
server:
  port: 8080

## Primary/Target Database Properties
spring:
  datasource:
    url: jdbc:mysql://172.16.10.177:13306/a1
    username: root
    password: 123456
  jpa.hibernate.ddl-auto: create-drop
  jpa.show-sql: true

## Source Database Properties
customer:
  datasource:
    host: 172.16.10.177
    port: 13306
    database: a2
    username: root
    password: 123456
