/*
 * Swagger Petstore This is a sample server Petstore server. You can find out more about Swagger at
 * [http://swagger.io](http://swagger.io) or on [irc.freenode.net,
 * #swagger](http://swagger.io/irc/). For this sample, you can use the api key `special-key` to test
 * the authorization filters.
 *
 * OpenAPI spec version: 1.0.0 Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class manually.
 */

package com.ymmihw.petstore.client.invoker;

import java.text.FieldPosition;
import java.util.Date;
import com.fasterxml.jackson.databind.util.StdDateFormat;


public class RFC3339DateFormat extends StdDateFormat {
  private static final long serialVersionUID = 1L;

  // Same as ISO8601DateFormat but serializing milliseconds.
  @Override
  public StringBuffer format(Date date, StringBuffer toAppendTo, FieldPosition fieldPosition) {
    @SuppressWarnings("deprecation")
    String value = com.fasterxml.jackson.databind.util.ISO8601Utils.format(date, true);
    toAppendTo.append(value);
    return toAppendTo;
  }

}
